build:
  image: ./bratly/dockerfiles/ci-images/uv:latest

  only:
    - tags

  variables:
    UV_PUBLISH_USERNAME: gitlab-ci-token
    UV_PUBLISH_PASSWORD: $CI_JOB_TOKEN
    UV_PUBLISH_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  script:
    #
    - echo ""
    - echo "Removing all src_* except src_libs and src_apps"
    - find . -type d -name "src_*" ! -name "src_libs" ! -name "src_apps" -exec rm -rf {} +
    #
    - echo ""
    - echo "Setting version to ${CI_COMMIT_TAG}"
    - |
      if [ -z "${CI_COMMIT_TAG}" ]; then
        echo "Error: CI_COMMIT_TAG is not set";
        exit 1;
      fi
    - find . -name "pyproject.toml" -exec toml set --toml-path {} project.version ${CI_COMMIT_TAG} \;
    #
    - echo ""
    - echo "Setting __version__ to each __init__.py files"
    - |
      find src_*/*/src/*/ -type f -name "__init__.py" | while read -r file; do \
        sed -i "1i __version__ = \"${CI_COMMIT_TAG}\"" "$file"; \
      done
    #
    - uv build --all
    - uv publish
